# Generated by Django 4.1.2 on 2022-12-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images', verbose_name='Ảnh đồ vật ( nếu có)'),
        ),
    ]
